import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ntuthuko Jr Mashinini - Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="about.js">About</a></li>
  <li><a href="#contact">Get in touch</a></li>
 
</ul>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ntuthuko Jr Mashinini
        </h1>
        <p>Tech Enthusiast | Software Engineer | Disruptor</p>

        <Image src="/ntuthuko.png" alt="Vercel Logo" width={400} height={400} />
        <div>
  <h2> <i>MEET NTUTHUKO</i></h2>
  <p><i>"You are as wise as to what you've been exposed to, Keep exposing yourself!" - Ntuthuko Jr Mashinini</i></p>
  <p ><b>Ntuthuko Jr Mashinini is a Software Engineer professional graduated at the Durban University of
technology. He is an ambitious young man that aims to build and uplift others as he rises. His goal is to be a well-renowned tech professional that has an excellent work ethic & incredible competency to enable him to be a catalyst for change & growth wherever he sets his footprint.</b>
  </p>
</div>
<br/>
<br/>
<div class="container">
      <div class="image">
      <Image src="/innovate.jpg" alt="Ntuthuko" width={1200} height={1450} />
      </div>
      <div class="text">
        <p>His success obtained from his Software Development projects at DUT afforded him the opportunity to work Durban’s innovation agency called <b>Innovate Durban</b> for Project Development.</p>
      </div>
    </div>
    <br/>
    <br/>
    <div class="container">
      <div class="text">
        <p>He has been invited to speak at The Durban
Business Fair <b>“Youth Seminar”</b> to share about a <b>"Kasi high school tour"</b> to
educate & create awareness about the future of tech, which aimed to guide learners on tech career choices.</p>
      </div>
      <div class="image">
      <Image src="/IMG_0476.jpg" alt="Ntuthuko" width={1200} height={1450} />
      </div>
    </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
